/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package connect4;

public class App {
    public static void main(String[] args) {
        Game game = new Game();
        game.start();
    }
}
